tasks:
  build:
    steps:
    - checkout
    - docker/build:
        image: registry.digitalocean.com/ruby-micro/demo
        tags: ["${CI_COMMIT_SHA:0:8}", "latest", "${CI_REPO_BRANCH}"]
        push: true

  deploy:
    depends: [build]
    variables:
    - DOCKER_TAG=${CI_COMMIT_SHA:0:8}
    steps:
    - commands:
      - kubectl -n default set image deployment.v1.apps/web web=registry.digitalocean.com/ruby-micro/demo:$DOCKER_TAG